update front

diff --git a/time_manager_front/Dockerfile b/time_manager_front/Dockerfile
--- a/time_manager_front/Dockerfile
+++ b/time_manager_front/Dockerfile
@@ -1,16 +1,11 @@
-# Étape de build
-FROM node:16-alpine as build-stage
-
-RUN apk add --no-cache npm
-
-
+FROM node:lts-alpine AS build-stage
 WORKDIR /app
 COPY package*.json ./
 RUN npm install
 COPY . .
-RUN npm run build
+RUN npm run build || (echo "Build failed" && npm run build --verbose && exit 1)
 
-FROM nginx:stable-alpine as production-stage
+FROM nginx:stable-alpine AS production-stage
 COPY --from=build-stage /app/dist /usr/share/nginx/html
 EXPOSE 80
 CMD ["nginx", "-g", "daemon off;"]
